name: CI Pipeline

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: npm builds
        runs-on: ubuntu-latest
        outputs:
          cache_hit: ${{ steps.set_cache_hit.outputs.cache_hit }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Setup cache
              uses: actions/cache@v4
              id: cache
              with:
                path: simple-reactjs-app-master/node_modules
                key: ${{ runner.os }}-${{ hashFiles('simple-reactjs-app-master/package-lock.json') }}

            - name: Set cache hit output
              id: set_cache_hit
              run: echo "cache_hit=${{ steps.cache.outputs.cache-hit }}" >> $GITHUB_ENV

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: cd simple-reactjs-app-master && npm install

            - name: Compile code
              run: cd simple-reactjs-app-master && npm run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: npm-build-artifact
                path: simple-reactjs-app-master/build

    lint:
        name: npm lint
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install dependencies
              if: needs.build.outputs.cache_hit != 'true'
              run: cd simple-reactjs-app-master && npm install

            - name: Run linting
              run: cd simple-reactjs-app-master && npm run test