name: CI Pipeline

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: npm builds
        needs:
          - audit
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: List directory contents
              run: ls -lah /home/runner/work/npm-labs/npm-labs/

            - name: Setup cache
              uses: actions/cache@v4
              id: cache
              with:
                path: simple-reactjs-app-master/node_modules
                key: ${{ runner.os }}-${{ hashFiles('simple-reactjs-app-master/package-lock.json') }}

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: cd simple-reactjs-app-master && npm install

            - name: Compile code
              run: cd simple-reactjs-app-master && npm run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: npm-build-artifact
                path: build
    
    audit:
      name: npm audit
      runs-on: ubuntu-latest

      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: audit check
            run: cd simple-reactjs-app-master && npm audit --audit-level=moderate

        
      
            

    

            
